### ISSUE TITLE
Easy glitch easy dupe Package

### ISSUE THREAD

**Issue by Gohu29** [MrCrayfish/MrCrayfishSkateboardingMod#2]
Hello i found a glitch in your mod. It's easy for dupe.
![glitch_package](https://cloud.githubusercontent.com/assets/13649609/9699621/1d51658e-53ea-11e5-8687-85a7f6c1e103.jpg)

**Comment by MrCrayfish** [comment]
Thanks. Will look into the issue

**Comment by MrCrayfish** [comment]
Wrong mod
