### ISSUE TITLE
plz help! issue with mod.

### ISSUE THREAD

**Issue by beybladep9** [MrCrayfish/MrCrayfishSkateboardingMod#4]
Whenever I destroy a block from your mod my game crashes.

these are the mods I have
![capture](https://cloud.githubusercontent.com/assets/22620001/19081098/bd81222c-8a1e-11e6-8124-0ea81fa36523.PNG)

this is the crash log
[crash-2016-10-04_10.22.19-client.txt](https://github.com/MrCrayfish/MrCrayfishSkateboardingMod/files/508879/crash-2016-10-04_10.22.19-client.txt)

**Comment by MrCrayfish** [comment]
It's a glitch with Optifine at the moment. I can make a temporary fix, however I'll probably submit a bug report to them.

**Comment by beybladep9** [comment]
Ok.
