### ISSUE TITLE
Updated to 1.11.2

### ISSUE THREAD

**Issue by ajacobsen** [MrCrayfish/MrCrayfishSkateboardingMod#5]
I update this mod to 1.11.2. If you are interested I can send you the new version or fork this repo and update it there or whatever you like :)
Btw: Thanks for publishing the source code! My sons really happy he can use this mod in 1.11.2 now :)

**Comment by stachutoziomal** [comment]
Hey. Can you send me that version? Or you can have version for 1.12.2? Please reply i really want that

**Comment by stachutoziomal** [comment]
> I update this mod to 1.11.2. If you are interested I can send you the new version or fork this repo and update it there or whatever you like :)
> Btw: Thanks for publishing the source code! My sons really happy he can use this mod in 1.11.2 now :)

.
